#include <Parsers/Polyglot/ParserPolyglotQuery.h>

#include "config.h"

#if USE_POLYGLOT
#    include <polyglot.h>
#endif

#include <Parsers/ParserQuery.h>
#include <Parsers/ParserSetQuery.h>
#include <Parsers/parseQuery.h>
#include <base/scope_guard.h>

namespace DB
{

namespace ErrorCodes
{
    extern const int SYNTAX_ERROR;
    extern const int SUPPORT_IS_DISABLED;
}

bool ParserPolyglotQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
{
    /// SET queries are standard ClickHouse SQL and must be handled normally
    /// so that settings like `dialect` and `polyglot_dialect` can be changed.
    ParserSetQuery set_p;
    if (set_p.parse(pos, node, expected))
        return true;

#if !USE_POLYGLOT
    throw Exception(
        ErrorCodes::SUPPORT_IS_DISABLED,
        "Polyglot SQL transpiler is not available. "
        "Rust code or polyglot itself may be disabled. Use another dialect!");
#else
    /// Pass the entire remaining input to polyglot as an opaque string.
    /// Foreign dialects may contain syntax that the ClickHouse Lexer cannot
    /// tokenize correctly, so we do not use the token stream at all.
    const char * begin = pos->begin;

    /// Advance the token iterator to the end so the caller knows we
    /// consumed all remaining input.
    while (!pos->isEnd())
        ++pos;

    /// Transpile the foreign SQL to ClickHouse SQL.
    uint8_t * sql_query_ptr{nullptr};
    uint64_t sql_query_size{0};

    const auto res = polyglot_transpile(
        reinterpret_cast<const uint8_t *>(begin),
        static_cast<uint64_t>(raw_end - begin),
        reinterpret_cast<const uint8_t *>(source_dialect.data()),
        static_cast<uint64_t>(source_dialect.size()),
        &sql_query_ptr,
        &sql_query_size);

    SCOPE_EXIT({ polyglot_free_pointer(sql_query_ptr); });

    const auto * sql_query_char_ptr = reinterpret_cast<char *>(sql_query_ptr);
    const auto * const original_sql_query_ptr = sql_query_char_ptr;

    if (res != 0)
        throw Exception(ErrorCodes::SYNTAX_ERROR, "Polyglot SQL transpilation error: '{}'", sql_query_char_ptr);

    chassert(sql_query_size > 0);

    /// Parse the transpiled ClickHouse SQL with the standard parser.
    ParserQuery query_p(sql_query_char_ptr + sql_query_size - 1, false);
    String error_message;
    node = tryParseQuery(
        query_p,
        sql_query_char_ptr,
        sql_query_char_ptr + sql_query_size - 1,
        error_message,
        false,
        "",
        false,
        max_query_size,
        max_parser_depth,
        max_parser_backtracks,
        true);

    if (!node)
        throw Exception(
            ErrorCodes::SYNTAX_ERROR,
            "Error while parsing the SQL query generated by polyglot transpiler: '{}'.\n"
            "Original query: '{}'\nTranspiled SQL: '{}'",
            error_message,
            std::string_view{begin, raw_end},
            std::string_view(original_sql_query_ptr, sql_query_size > 0 ? sql_query_size - 1 : 0));

    return true;
#endif
}

}
