#!/usr/bin/env bash

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

USER="u_${CLICKHOUSE_TEST_UNIQUE_NAME}"
PROFILE="p_${CLICKHOUSE_TEST_UNIQUE_NAME}"

${CLICKHOUSE_CLIENT} -q "DROP SETTINGS PROFILE IF EXISTS ${PROFILE}"
${CLICKHOUSE_CLIENT} -q "DROP USER IF EXISTS ${USER}"

${CLICKHOUSE_CLIENT} -q "CREATE USER ${USER}"
${CLICKHOUSE_CLIENT} -q "CREATE SETTINGS PROFILE ${PROFILE}"
${CLICKHOUSE_CLIENT} -q "ALTER USER ${USER} SETTINGS PROFILE ${PROFILE}"
${CLICKHOUSE_CLIENT} -q "SELECT * FROM system.settings_profile_elements WHERE user_name='${USER}' OR profile_name='${PROFILE}'" | sed "s/${USER}/USER/g; s/${PROFILE}/PROFILE/g"
${CLICKHOUSE_CLIENT} -q "DROP SETTINGS PROFILE ${PROFILE}"
${CLICKHOUSE_CLIENT} -q "SELECT 'PROFILE DROPPED'"
${CLICKHOUSE_CLIENT} -q "SELECT * FROM system.settings_profile_elements WHERE user_name='${USER}' OR profile_name='${PROFILE}'" | sed "s/${USER}/USER/g; s/${PROFILE}/PROFILE/g"

${CLICKHOUSE_CLIENT} -q "DROP USER IF EXISTS ${USER}"
${CLICKHOUSE_CLIENT} -q "DROP SETTINGS PROFILE IF EXISTS ${PROFILE}"
