-- Tests for SYSTEM commands that lacked coverage in InterpreterSystemQuery.cpp.
-- Covers: CLEAR_PRIMARY_INDEX_CACHE, CLEAR_PAGE_CACHE, START/STOP_THREAD_FUZZER,
-- RELOAD_FUNCTIONS, RELOAD_EMBEDDED_DICTIONARIES.

SYSTEM DROP PRIMARY INDEX CACHE;
SYSTEM CLEAR PRIMARY INDEX CACHE;

SYSTEM DROP PAGE CACHE;
SYSTEM CLEAR PAGE CACHE;

SYSTEM STOP THREAD FUZZER;
SYSTEM START THREAD FUZZER;

SYSTEM RELOAD FUNCTIONS;
SYSTEM RELOAD EMBEDDED DICTIONARIES;
